
package infixpostfix;

import buttons.CloseBTN;
import buttons.MinimizeBTN;
import com.k33ptoo.components.KButton;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Christian
 */
public class InfixToPostfixGUI extends javax.swing.JFrame {
    
    
    
    public InfixToPostfixGUI(int mousepX, int mousepY, JLabel Background, KButton ConvertBTN,
            JTextField InfixText, JLabel MouseDrag, JTextField PostfixText, JLabel Result,
            JLabel Table, JLabel Text, JLabel Text1, JLabel Text3, JLabel Text4, JLabel Time,
            CloseBTN closeBTN, JLabel jLabel2, JLabel jLabel5, JLabel jLabel6, JLabel jLabel7,
            JLabel jLabel8, JPanel jPanel1, MinimizeBTN minimizeBTN) throws HeadlessException {
        this.mousepX = mousepX;
        this.mousepY = mousepY;
        this.Background = Background;
        this.ConvertBTN = ConvertBTN;
        this.InfixText = InfixText;
        this.MouseDrag = MouseDrag;
        this.PostfixText = PostfixText;
        this.Result = Result;
        this.Text = Text;
        this.Text1 = Text1;
        this.Text3 = Text3;
        this.Text4 = Text4;
        this.Time = Time;
        this.closeBTN = closeBTN;
        this.jLabel2 = jLabel2;
        this.jLabel5 = jLabel5;
        this.jLabel6 = jLabel6;
        this.jLabel7 = jLabel7;
        this.jLabel8 = jLabel8;
        this.jPanel1 = jPanel1;
        this.minimizeBTN = minimizeBTN;
        this.Table = Table;
    }
    
    String infix = "";
    int mousepX, mousepY;
    public InfixToPostfixGUI() {
        initComponents();
        jPanel1.setFocusable(true);
        this.setBackground(new Color(0,0,0,1));
        InfixText.setBackground(new Color(0,0,0,1));
        PostfixText.setBackground(new Color(0,0,0,1));
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 58, 58));
        closeBTN.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InfixText = new javax.swing.JTextField();
        PostfixText = new javax.swing.JTextField();
        ConvertBTN = new com.k33ptoo.components.KButton();
        closeBTN = new buttons.CloseBTN();
        minimizeBTN = new buttons.MinimizeBTN();
        Table = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MouseDrag = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        InfixText.setBackground(new java.awt.Color(0, 0, 0));
        InfixText.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        InfixText.setForeground(new java.awt.Color(84, 84, 84));
        InfixText.setText("Enter Infix Expression");
        InfixText.setBorder(null);
        InfixText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InfixTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InfixTextFocusLost(evt);
            }
        });
        InfixText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfixTextActionPerformed(evt);
            }
        });
        jPanel1.add(InfixText);
        InfixText.setBounds(360, 310, 260, 40);

        PostfixText.setBackground(new java.awt.Color(255, 255, 255));
        PostfixText.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        PostfixText.setForeground(new java.awt.Color(84, 84, 84));
        PostfixText.setText("Postfix Expression is...");
        PostfixText.setBorder(null);
        PostfixText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PostfixTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PostfixTextFocusLost(evt);
            }
        });
        PostfixText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostfixTextActionPerformed(evt);
            }
        });
        jPanel1.add(PostfixText);
        PostfixText.setBounds(360, 400, 260, 40);

        ConvertBTN.setForeground(new java.awt.Color(153, 153, 153));
        ConvertBTN.setText("Convert");
        ConvertBTN.setBorderPainted(false);
        ConvertBTN.setFocusable(false);
        ConvertBTN.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        ConvertBTN.setkBorderRadius(40);
        ConvertBTN.setkEndColor(new java.awt.Color(51, 51, 51));
        ConvertBTN.setkForeGround(new java.awt.Color(204, 204, 204));
        ConvertBTN.setkHoverEndColor(new java.awt.Color(55, 55, 65));
        ConvertBTN.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        ConvertBTN.setkHoverStartColor(new java.awt.Color(66, 65, 71));
        ConvertBTN.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        ConvertBTN.setkPressedColor(new java.awt.Color(107, 107, 107));
        ConvertBTN.setkStartColor(new java.awt.Color(61, 61, 61));
        ConvertBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ConvertBTN);
        ConvertBTN.setBounds(410, 550, 150, 45);

        closeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 1 (1).png"))); // NOI18N
        closeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBTNMouseClicked(evt);
            }
        });
        jPanel1.add(closeBTN);
        closeBTN.setBounds(920, 0, 50, 20);

        minimizeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Line 4_1.png"))); // NOI18N
        minimizeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBTNMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBTN);
        minimizeBTN.setBounds(870, 0, 50, 20);

        Table.setFont(new java.awt.Font("Poppins Medium", 2, 14)); // NOI18N
        Table.setForeground(new java.awt.Color(215, 215, 215));
        Table.setText("VIew Table");
        Table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TableMouseReleased(evt);
            }
        });
        jPanel1.add(Table);
        Table.setBounds(450, 620, 90, 20);
        jPanel1.add(Time);
        Time.setBounds(270, 210, 110, 20);

        Text.setBackground(new java.awt.Color(255, 255, 255));
        Text.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        Text.setForeground(new java.awt.Color(204, 204, 204));
        Text.setText("Result");
        jPanel1.add(Text);
        Text.setBounds(350, 450, 260, 40);

        Text1.setBackground(new java.awt.Color(255, 255, 255));
        Text1.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        Text1.setForeground(new java.awt.Color(204, 204, 204));
        Text1.setText("Postfix expression");
        jPanel1.add(Text1);
        Text1.setBounds(350, 360, 260, 40);

        Text3.setBackground(new java.awt.Color(255, 255, 255));
        Text3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Text3.setForeground(new java.awt.Color(84, 84, 84));
        Text3.setText("Result");
        jPanel1.add(Text3);
        Text3.setBounds(360, 490, 260, 40);

        Text4.setBackground(new java.awt.Color(255, 255, 255));
        Text4.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        Text4.setForeground(new java.awt.Color(204, 204, 204));
        Text4.setText("Infix Expression ");
        jPanel1.add(Text4);
        Text4.setBounds(350, 270, 140, 40);
        jPanel1.add(Result);
        Result.setBounds(350, 490, 280, 30);

        jLabel6.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(227, 227, 227));
        jLabel6.setText("Infix to Postfix Converter");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 60, 490, 55);

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(218, 217, 217));
        jLabel7.setText("Infix to Postfix Calculator");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 10, 160, 19);

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(218, 217, 217));
        jLabel8.setText("This is a simple infix to prefix or postfix Converter.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 120, 400, 25);

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(218, 217, 217));
        jLabel5.setText("Enter the Infix expression below in box and press Convert");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 140, 470, 30);

        MouseDrag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MouseDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MouseDragMouseDragged(evt);
            }
        });
        MouseDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MouseDragMousePressed(evt);
            }
        });
        jPanel1.add(MouseDrag);
        MouseDrag.setBounds(0, 0, 1000, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calculator (2).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 70, 620, 620);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Desktop_2.png"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1000, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(998, 779));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InfixTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InfixTextFocusGained
        if(InfixText.getText().equals("Enter Infix Expression")){
            InfixText.setText("");
        }
        InfixText.setForeground(new Color(183,173,173));
    }//GEN-LAST:event_InfixTextFocusGained

    private void InfixTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InfixTextFocusLost
        if(InfixText.getText().equals("")){
            InfixText.setText("Enter Infix Expression");
            InfixText.setForeground(new Color(84,84,84));
        }
    }//GEN-LAST:event_InfixTextFocusLost

    private void InfixTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfixTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfixTextActionPerformed

    private void PostfixTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PostfixTextFocusGained

    }//GEN-LAST:event_PostfixTextFocusGained

    private void PostfixTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PostfixTextFocusLost

    }//GEN-LAST:event_PostfixTextFocusLost

    private void PostfixTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostfixTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostfixTextActionPerformed

    private void MouseDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseDragMouseDragged
        int CordinateX = evt.getXOnScreen();
        int CordinateY = evt.getYOnScreen();

        this.setLocation(CordinateX-mousepX, CordinateY-mousepY);
    }//GEN-LAST:event_MouseDragMouseDragged

    private void MouseDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseDragMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_MouseDragMousePressed

    private void ConvertBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertBTNActionPerformed
        String infix = InfixText.getText();
        this.infix = infix;
        
        InfixToPostfixCalculator obj = new InfixToPostfixCalculator(infix);
        
        String postfix = obj.displayPostfix();
        PostfixText.setText(obj.displayPostfix());
        PostfixText.setForeground(new Color(183,173,173));
        
        double result = InfixToPostfixCalculator.showResult(postfix);
        
        Text3.setText(String.format("%,.2f", result));
        Text3.setForeground(new Color(183,173,173));
        
        
    }//GEN-LAST:event_ConvertBTNActionPerformed
        
    private void closeBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBTNMouseClicked
        dispose();
    }//GEN-LAST:event_closeBTNMouseClicked

    private void minimizeBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBTNMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBTNMouseClicked

    private void TableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseReleased
        new Table(infix.replace(" ", "")).show();
    }//GEN-LAST:event_TableMouseReleased

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked

        new Table(infix.replace(" ", "")).show();
    }//GEN-LAST:event_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfixToPostfixGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfixToPostfixGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfixToPostfixGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfixToPostfixGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfixToPostfixGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private com.k33ptoo.components.KButton ConvertBTN;
    private javax.swing.JTextField InfixText;
    private javax.swing.JLabel MouseDrag;
    private javax.swing.JTextField PostfixText;
    private javax.swing.JLabel Result;
    private javax.swing.JLabel Table;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Time;
    private buttons.CloseBTN closeBTN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private buttons.MinimizeBTN minimizeBTN;
    // End of variables declaration//GEN-END:variables
}
